-- MySQL Script generated by MySQL Workbench
-- Sun Nov 12 21:26:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- Database by @R0nVBaldor
-- attemp_xsy dev@again
-- Author: Ronaldo S.M.

-- Modelo de base de datos : Medico-Hospital Administrativo
-- 15/04/24 se actualizo medidas y campos de protocolos de comunicacion.
-- Model: New Model    Version: 3.2


SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospital e
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS Admhospital;
USE AdmHospital;
-- -----------------------------------------------------
-- Table `hospital`.`paciente`
-- -----------------------------------------------------

CREATE TABLE `paciente` (
  `IDPaciente` INT NOT NULL,
  `Nombre` TEXT NULL DEFAULT NULL,
  `Apellido` TEXT NULL DEFAULT NULL,
  `FechaNacimiento` DATE NULL DEFAULT NULL,
  `Genero` TEXT NULL DEFAULT NULL,
  `Direccion` TEXT NULL DEFAULT NULL,
  `Telefono` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IDPaciente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS paciente;

DESCRIBE `paciente`;

INSERT INTO paciente(IDPaciente, Nombre, Apellido, FechaNacimiento, Genero, Direccion, Telefono) VALUES(010, "kevin", "Balboa", "2003-07-01" , "Masculino", "EntreRios N14" ,"74489566");
INSERT INTO paciente(IDPaciente, Nombre, Apellido, FechaNacimiento, Genero, Direccion, Telefono) VALUES (012, 'John', 'Doe', '1990-03-15', 'Masculino', '123 Main St', '555-1234');
INSERT INTO paciente (IDPaciente, Nombre, Apellido, FechaNacimiento, Genero, Direccion, Telefono)
VALUES
(001, 'Alice', 'Smith', '1985-08-21', 'Femenino', '456 Oak St', '+591 74458951'),
(002, 'Bob', 'Johnson', '1979-05-10', 'Masculino', '789 Pine St', '+55 555-9876'),
(003, 'Eva', 'Williams', '1995-11-30', 'Femenino', '101 Elm St', '+531 575-3456'),
(004, 'Charlie', 'Brown', '1982-02-17', 'Masculino', '202 Maple St', '555-7890'),
(005, 'Sophia', 'Miller', '1993-09-05', 'Femenino', '303 Cedar St', '555-2345'),
(006, 'Mason', 'Davis', '1988-12-12', 'Masculino', '404 Birch St', '555-6789'),
(007, 'Olivia', 'Garcia', '1999-04-02', 'Femenino', '505 Walnut St', '555-1234'),
(008, 'Liam', 'Martinez', '1980-07-18', 'Masculino', '606 Pine St', '555-5678');

SELECT* FROM paciente;


-- -----------------------------------------------------
-- Table `hospital`.`medico`
-- -----------------------------------------------------
CREATE TABLE `medico` (
  `IDMedico` INT NOT NULL,
  `Nombre` TEXT NULL DEFAULT NULL,
  `Apellido` TEXT NULL DEFAULT NULL,
  `Especialidad` TEXT NULL DEFAULT NULL,
  `Telefono` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IDMedico`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS medico;

DESCRIBE medico;

INSERT INTO medico (IDMedico, Nombre, Apellido, Especialidad, Telefono) VALUES (015, 'NombreMedico', 'ApellidoMedico', 'EspecialidadMedico', 'TelefonoMedico');
INSERT INTO medico (IDMedico, Nombre, Apellido, Especialidad, Telefono) VALUES (018, 'Dr. Smith', 'Johnson', 'Cardiología', '555-5678');
INSERT INTO medico (IDMedico, Nombre, Apellido, Especialidad, Telefono)
VALUES
(701, 'Dr. Laura', 'Gonzalez', 'Neurología', '555-1111'),
(702, 'Dra. Samuel', 'Rodriguez', 'Ginecología', '555-2222'),
(703, 'Dr. Sophia', 'Lopez', 'Pediatría', '555-3333'),
(704, 'Dra. James', 'Hernandez', 'Cardiología', '555-4444'),
(705, 'Dr. Emma', 'Gomez', 'Dermatología', '555-5555'),
(706, 'Dra. William', 'Perez', 'Oftalmología', '555-6666'),
(707, 'Dr. Mia', 'Torres', 'Ortopedia', '555-7777'),
(708, 'Dra. Daniel', 'Flores', 'Endocrinología', '555-8888');


SELECT* FROM medico;
-- -----------------------------------------------------
-- Table `hospital`.`enfermera`
-- -----------------------------------------------------
CREATE TABLE `enfermera` (
  `IDEnfermera` INT NOT NULL,
  `Nombre` TEXT NULL DEFAULT NULL,
  `Apellido` TEXT NULL DEFAULT NULL,
  `Telefono` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IDEnfermera`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS enfermera; 

describe enfermera;

INSERT INTO enfermera (IDEnfermera, Nombre, Apellido, Telefono) VALUES (14, 'Clementine', 'Emerg', 'TelefonoEnfermera');
INSERT INTO enfermera (IDEnfermera, Nombre, Apellido, Telefono) VALUES (17, 'Elizabeth', 'Davis', '555-9876');

INSERT INTO enfermera (IDEnfermera, Nombre, Apellido, Telefono)
VALUES
(15, 'Enfermera Maria', 'Garcia', '555-1111'),
(16, 'Enfermero Juan', 'Lopez', '555-2222'),
(25, 'Enfermera Ana', 'Perez', '555-3333'),
(18, 'Enfermero Carlos', 'Rodriguez', '555-4444'),
(19, 'Enfermera David', 'Torres', '555-5555'),
(20, 'Enfermero Laura', 'Hernandez', '555-6666'),
(21, 'Enfermera Luisa', 'Martinez', '555-7777'),
(22, 'Enfermero Diego', 'Gomez', '555-8888');

SELECT* FROM enfermera;

-- -----------------------------------------------------
-- Table `hospital`.`consulta`
-- -----------------------------------------------------
CREATE TABLE `consulta` (
  `IDConsulta` INT NOT NULL,
  `IDPaciente` INT NULL DEFAULT NULL,
  `IDMedico` INT NULL DEFAULT NULL,
  `IDEnfermera` INT NULL DEFAULT NULL,
  `FechaHoraConsulta` DATETIME NULL DEFAULT NULL,
  `Sintomas` TEXT NULL DEFAULT NULL,
  `Observaciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IDConsulta`),
  INDEX `IDPaciente` (`IDPaciente` ASC) VISIBLE,
  INDEX `IDMedico` (`IDMedico` ASC) VISIBLE,
  INDEX `IDEnfermera` (`IDEnfermera` ASC) VISIBLE,
  CONSTRAINT `consulta_ibfk_1`
    FOREIGN KEY (`IDPaciente`)
    REFERENCES `admhospital`.`paciente` (`IDPaciente`),
  CONSTRAINT `consulta_ibfk_2`
    FOREIGN KEY (`IDMedico`)
    REFERENCES `admhospital`.`medico` (`IDMedico`),
  CONSTRAINT `consulta_ibfk_3`
    FOREIGN KEY (`IDEnfermera`)
    REFERENCES `admhospital`.`enfermera` (`IDEnfermera`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

DROP TABLE IF EXISTS consulta;

DESCRIBE consulta;

INSERT INTO consulta(IDConsulta,IDPaciente,IDMedico ,IDEnfermera, FechaHoraConsulta,Sintomas, Observaciones) VALUES(001, 002, 703, 22, "10-11-23", "El paciente presenta sintomas saludables", "presenta un estado de salud bastante normal ,saludable");
INSERT INTO consulta (IDConsulta, IDPaciente, IDMedico, IDEnfermera, FechaHoraConsulta, Sintomas, Observaciones)
VALUES
-- Paciente Z
(001, 002, 702, 22, '2023-01-01 08:00:00', 'Dolor de cabeza', 'Observaciones 1'),
(002, 005, 701, 18, '2023-02-10 10:30:00', 'Fiebre', 'Observaciones 2'),
(003, 004, 704, 17, '2023-03-20 14:45:00', 'Dolor de garganta', 'Observaciones 3'),
(004, 003, 706, 16, '2023-04-05 09:15:00', 'Fatiga', 'Observaciones 4'),
(005, 001, 708, 16, '2023-05-12 11:30:00', 'Problemas respiratorios', 'Observaciones 5'),
(006, 007, 709, 16, '2023-06-18 13:20:00', 'Dolor abdominal', 'Observaciones 6'),
(007, 006, 706, 13, '2023-07-25 16:10:00', 'Mareos', 'Observaciones 7'),
(008, 008, 703, 21, '2023-08-30 09:45:00', 'Dolor en las articulaciones', 'Observaciones 8'),
(009, 010, 709, 22, '2023-09-12 10:00:00', 'Dolor de espalda', 'Observaciones 9'),
(010, 015, 705, 22, '2023-10-05 15:30:00', 'Problemas digestivos', 'Observaciones 10');
SELECT* FROM consulta;

-- -----------------------------------------------------
-- Table `hospital`.`medicologin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdmHospital`.`medicologin` (
  `Nombre` VARCHAR(35) NOT NULL,
  `Especialidad` VARCHAR(35) NOT NULL,
  `Passwordd` VARCHAR(25) NOT NULL,
  `Fechaext` DATE,
  PRIMARY KEY (`Nombre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- insert to 'triagedbox'.'medicologin' 

DROP TABLE IF EXISTS `medicologin`;


DESCRIBE medicologin;

INSERT INTO medicologin(`Nombre`, `Especialidad`, `Passwordd`, `Fechaext`) VALUES("kevin", "Cirujano", "devloop","10-10-23" );
INSERT INTO medicologin(`Nombre`, `Especialidad`, `Passwordd`, `Fechaext`) VALUES("admin", "admin", "admin","10-10-23" );


INSERT INTO medicologin (Nombre, Especialidad, Passwordd, Fechaext) VALUES ('Carlos', 'Cirujia', 'ContraseñaMedico', '2023-11-17');
SELECT* FROM medicologin;

-- -----------------------------------------------------
-- Table `hospital`.`Enfermeralogin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdmHospital`.`enfermeralogin` (
  `Nombre` VARCHAR(35) NOT NULL,
  `Cargo` VARCHAR(35) NOT NULL,
  `Passwordd` VARCHAR(25) NOT NULL,
  `Fechaext` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`Nombre`))
  
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `enfermeralogin`;

DESCRIBE enfermeralogin;

INSERT INTO enfermeralogin (Nombre, Cargo, Passwordd, Fechaext)
VALUES ('Ana', 'AsistenteR2', 'ContraseñaEnfermera', '2023-11-15');
INSERT INTO enfermeralogin (Nombre, Cargo, Passwordd, Fechaext)
VALUES
('Olivia', 'Enfermera Principal', 'PassEnf1', '2023-11-15'),
('Emiliano', 'Enfermero Jefe', 'PassEnf2', '2023-11-15'),
('Carmen', 'Enfermera de Turno', 'PassEnf3', '2023-11-15'),
('Roger', 'Enfermero de Guardia', 'PassEnf4', '2023-11-15'),
('Maria', 'Enfermera de Urgencias', 'PassEnf5', '2023-11-15'),
('Mateo', 'Enfermero de Cirugía', 'PassEnf6', '2023-11-15'),
('Georgina', 'Enfermera de Maternidad', 'PassEnf7', '2023-11-15'),
('Carlos', 'Enfermero de Pediatría', 'PassEnf8', '2023-11-15');

SELECT* FROM enfermeralogin;
-- -----------------------------------------------------
-- Table `hospital`.`tipo_signo_vital`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AdmHospital`.`tipo_signo_vital` (
  `IDTipoSignoVital` INT NOT NULL,
  `Nombre` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`IDTipoSignoVital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `tipo_signo_vital`;

DESCRIBE tipo_signo_vital;


INSERT INTO tipo_signo_vital (IDTipoSignoVital, Nombre)
VALUES
(001, 'Presión Arterial'),
(002, 'Frecuencia Cardíaca'),
(003, 'Temperatura Corporal'),
(004, 'Nivel de Oxígeno en Sangre'),
(005, 'Glucosa'),
(006, 'Peso Corporal'),
(007, 'Altura'),
(008, 'Índice de Masa Corporal');

SELECT* FROM tipo_signo_vital;

-- -----------------------------------------------------
-- Table `hospital`.`registro_signos_vitales`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `admhospital`.`registro_signos_vitales` (
  `IDRegistro` INT NOT NULL,
  `IDPaciente` INT NOT NULL,
  `IDTipoSignoVital` INT NOT NULL,
  `Valor` DECIMAL(10,2) NOT NULL,
  `FechaHoraRegistro` DATETIME NOT NULL,
  PRIMARY KEY (`IDRegistro`),
  INDEX `IDPaciente` (`IDPaciente` ASC) VISIBLE,
  INDEX `IDTipoSignoVital` (`IDTipoSignoVital` ASC) VISIBLE,
  CONSTRAINT `registro_signos_vitales_ibfk_1`
    FOREIGN KEY (`IDPaciente`)
    REFERENCES `admhospital`.`paciente` (`IDPaciente`),
  CONSTRAINT `registro_signos_vitales_ibfk_2`
    FOREIGN KEY (`IDTipoSignoVital`)
    REFERENCES `admhospital`.`tipo_signo_vital` (`IDTipoSignoVital`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


DROP TABLE IF EXISTS `registro_signos_vitales`;

DESCRIBE registro_signos_vitales;



INSERT INTO registro_signos_vitales (IDRegistro, IDPaciente, IDTipoSignoVital, Valor, FechaHoraRegistro)
VALUES
(1, 001, 1, 120/80, '2023-11-15 08:30:00'),
(2, 002, 2, 75, '2023-11-15 09:15:00'),
(3, 003, 3, 98.6, '2023-11-15 10:00:00'),
(4, 004, 4, 98, '2023-11-15 11:00:00'),
(5, 005, 5, 90, '2023-11-15 12:30:00'),
(6, 006, 6, 70, '2023-11-15 13:45:00'),
(7, 007, 7, 170, '2023-11-15 15:00:00'),
(8, 008, 8, 24, '2023-11-15 16:30:00');

;
SELECT* FROM registro_signos_vitales;

-- -----------------------------------------------------
-- Table `hospital`.`resultadoconsulta`
-- -----------------------------------------------------
CREATE TABLE  resultadoconsulta (
  `IDResultado` INT NOT NULL,
  `IDConsulta` INT NULL DEFAULT NULL,
  `Diagnostico` TEXT NULL DEFAULT NULL,
  `TratamientoRecomendado` TEXT NULL DEFAULT NULL,
  `Prescripciones` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`IDResultado`),
  INDEX `IDConsulta` (`IDConsulta` ASC) VISIBLE,
  CONSTRAINT `resultadoconsulta_ibfk_1`
    FOREIGN KEY (`IDConsulta`)
    REFERENCES `admhospital`.`consulta` (`IDConsulta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



DROP TABLE IF EXISTS resultadoconsulta ;

INSERT INTO resultadoconsulta (IDResultado, IDConsulta, Diagnostico, TratamientoRecomendado, Prescripciones)
VALUES
(001, 002, 'Migraña leve', 'Reposo y analgésicos', 'Paracetamol 500mg cada 6 horas'),
(002, 003, 'Resfriado común', 'Reposo y líquidos', 'Ibuprofeno 400mg cada 8 horas'),
(003, 004, 'Infección respiratoria', 'Antibióticos y reposo', 'Amoxicilina 500mg cada 12 horas'),
(005, 005, 'Posible problema cardíaco', 'Derivación a cardiólogo', "AtencionMed"),
(004, 006, 'Dermatitis leve', 'Crema y evitar irritantes', 'Crema hidratante y antialérgica'),
(006, 007, 'Artritis leve', 'Análisis de sangre y reposo', 'Ibuprofeno 600mg cada 8 horas'),
(007, 008, 'Miopía', 'Prescripción de anteojos', 'N/A'),
(008, 009, 'Indigestión', 'Dieta y medicamentos', 'Omeprazol 20mg cada 24 horas');

describe resultadoconsulta;

SELECT* FROM resultadoconsulta;

ALTER TABLE `admhospital`.`medicologin` 
ADD COLUMN `IDMedico` INT NOT NULL,
ADD CONSTRAINT `medicologin_ibfk_1` FOREIGN KEY (`IDMedico`) REFERENCES `admhospital`.`medico` (`IDMedico`);

ALTER TABLE `admhospital`.`enfermeralogin` 
ADD COLUMN `IDEnfermera` INT NOT NULL,
ADD CONSTRAINT `enfermeralogin_ibfk_1` FOREIGN KEY (`IDEnfermera`) REFERENCES `admhospital`.`enfermera` (`IDEnfermera`);



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


